# Generated by Django 5.2.1 on 2025-05-14 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahanaapp', '0002_webpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='internal_links',
            new_name='links',
        ),
        migrations.AddField(
            model_name='webpage',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(default='No Content'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
