# Generated by Django 5.2.1 on 2025-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahanaapp', '0003_rename_internal_links_webpage_links_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='links',
            new_name='internal_links',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
