# Generated by Django 5.2.1 on 2025-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahanaapp', '0004_rename_links_webpage_internal_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='external_links',
            field=models.JSONField(default=list),
        ),
    ]
