# Generated by Django 5.2.1 on 2025-05-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahanaapp', '0005_webpage_external_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
