# Generated by Django 5.2.1 on 2025-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahanaapp', '0006_webpage_embedding_alter_webpage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='chunks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
