# Generated by Django 5.2.1 on 2025-05-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahanaapp', '0007_webpage_chunks_alter_webpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='chunks',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='embedding',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
