# Generated by Django 5.2.1 on 2025-05-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahanaapp', '0008_remove_webpage_chunks_remove_webpage_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
